version: '3.8'

services:
  caddy2:
    image: ericwang2006/caddy2
    container_name: caddy2
    restart: always
    network_mode: "host"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN:-example.com}
      - EMAIL=${EMAIL:-admin@example.com}
